global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
      
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "scheduler"
    static_configs:
      - targets: ["downloader:8000"]

  - job_name: "pushgateway"
    static_configs:
      - targets: ["pushgateway:9091"]

  - job_name: "parser"
    static_configs:
      - targets: ["parser:8002"]
